"""add phone number to user model

Revision ID: 45556d3d1843
Revises: 
Create Date: 2026-06-03 15:43:24.565384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45556d3d1843'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        
    # ### end Alembic commands ###
